package com.gawi.core.ui.component

import androidx.annotation.DrawableRes
import com.gawi.core.ui.R

/**
 * The app's icon set: Lucide, vendored as VectorDrawables in this module.
 *
 * **Why ids here rather than `R.drawable.*` at the call sites.** AGP's
 * non-transitive R classes mean a feature module reaching a `:core:ui` drawable
 * has to `import com.gawi.core.ui.R`, which collides with its own `R` and reads
 * like a mistake. One accessor object keeps that import on this side, the same
 * way [GawiIconButton] keeps `stringResource` on the caller's.
 *
 * **Why vendored and not a dependency.** Lucide publishes no Android artifact,
 * so the choice was vendoring or nothing. Ten files of about 300 bytes,
 * generated by `scripts/convert-lucide.py` from a pinned `lucide-static`, and
 * reviewable in the diff. `material-icons-extended` is the alternative, and
 * the trade [GawiIconButton]'s KDoc argues against for the dependency it names.
 *
 * **Licensing is not uniform and the notice covers both halves.** Lucide is ISC;
 * six of these ten derive from Feather and are additionally MIT. Each drawable
 * says which it is, and `licenses/Lucide-ISC.txt` carries both texts verbatim.
 * Nothing packages that directory yet — the licences surface is a release gate
 * this does not close (docs/ux/visual-identity.md §7.5).
 *
 * **Arrows navigate, chevrons step.** [ArrowLeft] is Up — it leaves the screen.
 * [ChevronLeft] and [ChevronRight] move a value within one, as the history
 * screen's month pager does. The two are not interchangeable and the difference
 * is the only thing here a reader has to remember.
 */
object GawiIcons {

    /** Up navigation, in five app bars. Not the month pager — see [ChevronLeft]. */
    @DrawableRes val ArrowLeft = R.drawable.ic_arrow_left

    /** Insights. Lucide `chart-pie`, which is what `◔` was reaching for. */
    @DrawableRes val ChartPie = R.drawable.ic_chart_pie

    /** A step back through a range, not a screen. */
    @DrawableRes val ChevronLeft = R.drawable.ic_chevron_left

    /** A step forward through a range, not a screen. */
    @DrawableRes val ChevronRight = R.drawable.ic_chevron_right

    /** Dismiss without saving. Lucide `x`, named for the job it does. */
    @DrawableRes val Close = R.drawable.ic_close

    /**
     * Manage habits. Lucide `list-checks` rather than `menu`: `☰` implied a
     * navigation drawer this app does not have, and the destination is a list
     * of things you tick.
     */
    @DrawableRes val ListChecks = R.drawable.ic_list_checks

    /** Decrement. Replaces `−` (U+2212), which Outfit did have. */
    @DrawableRes val Minus = R.drawable.ic_minus

    /** Edit. */
    @DrawableRes val Pencil = R.drawable.ic_pencil

    /** Increment. */
    @DrawableRes val Plus = R.drawable.ic_plus

    /** Settings. */
    @DrawableRes val Settings = R.drawable.ic_settings

    /**
     * Every icon in the set, in one list.
     *
     * This exists for `GawiIconsTest`, which sweeps the generated XML and
     * cannot otherwise know how many files to expect — a count it has to get
     * from somewhere other than the directory it is checking, or it would pass
     * on an empty one. It also means a drawable added to `res/` without being
     * exposed here fails a test instead of sitting unused.
     *
     * `internal` because that is the whole of its audience. Kotlin makes it
     * visible to this module's unit tests, and a feature module has no use for
     * a list of every icon — it reaches for the one it draws by name.
     */
    internal val all = listOf(
        ArrowLeft, ChartPie, ChevronLeft, ChevronRight, Close,
        ListChecks, Minus, Pencil, Plus, Settings,
    )
}
