#!/usr/bin/env python3
"""Convert Lucide SVGs into the VectorDrawables :core:ui draws.

Run this rather than hand-editing anything in core/ui/src/main/res/drawable.
It needs python3 and network access; it is a developer tool, not part of the
build, so CI never runs it and `make` does not know about it.

    scripts/convert-lucide.py                 # fetch the pinned version
    scripts/convert-lucide.py --svg-dir DIR   # convert an already-fetched copy

**The version is pinned on purpose.** Lucide v1 renamed icons (`pie-chart` ->
`chart-pie`, still aliased), so `@latest` would make the checked-in files
irreproducible and a re-run could silently redraw the app.

**Why a conversion step at all.** Lucide publishes no Android artifact, so the
choice is vendoring or nothing. Ten files of about 300 bytes, converted once
and reviewable in the diff, beats a hand-drawn set nobody can re-derive.

**The guard is the point.** `VectorDrawable` has no element for <circle>,
<rect>, <line>, <polyline> or <polygon>, and an SVG carrying one would
otherwise convert with that part of the drawing silently missing. <circle> is
converted exactly (see below); anything else is a hard failure asking for a
deliberate conversion rather than a quiet drop. This is not hypothetical:
`settings` in 1.34.0 is one path plus one circle.
"""

import argparse
import os
import sys
import urllib.request
import xml.etree.ElementTree as ET

VERSION = "1.34.0"
BASE = "https://unpkg.com/lucide-static@" + VERSION
NS = "{http://www.w3.org/2000/svg}"
OUT = os.path.join("core", "ui", "src", "main", "res", "drawable")

# Lucide slug -> drawable name. `x` becomes ic_close because the drawable is
# named for the job, not the glyph; every other name matches its source.
ICONS = {
    "arrow-left": "ic_arrow_left",
    "chart-pie": "ic_chart_pie",
    "chevron-left": "ic_chevron_left",
    "chevron-right": "ic_chevron_right",
    "list-checks": "ic_list_checks",
    "minus": "ic_minus",
    "pencil": "ic_pencil",
    "plus": "ic_plus",
    "settings": "ic_settings",
    "x": "ic_close",
}

# The icons licenses/Lucide-ISC.txt lists as derived from Feather, which adds
# MIT to their ISC. Six of the ten, so it is worth stating per file.
FEATHER = {"arrow-left", "chevron-left", "chevron-right", "minus", "plus", "x"}

HEADER = """<?xml version="1.0" encoding="utf-8"?>
<!--
    Lucide `{slug}`, converted from lucide-static {version}.
    {licence}

    Generated by scripts/convert-lucide.py, not hand-drawn. Re-run it against
    the pinned version rather than tuning the path data here.{note}
-->
<vector xmlns:android="http://schemas.android.com/apk/res/android"
    android:width="24dp"
    android:height="24dp"
    android:viewportWidth="24"
    android:viewportHeight="24">
"""

PATH = """    <path
        android:pathData="{d}"
        android:strokeWidth="2"
        android:strokeColor="#FF000000"
        android:strokeLineCap="round"
        android:strokeLineJoin="round" />
"""

CIRCLE_NOTE = """

    The source's <circle cx="{cx}" cy="{cy}" r="{r}"> is the second path
    below. VectorDrawable has no circle element, and the substitution is
    exact rather than an approximation: an elliptical arc with rx = ry = r
    and the large-arc flag set traces a true semicircle, so two of them
    close the figure."""


def trim(value):
    """3.0 -> 3, so generated path data reads like the hand-written kind."""
    return "%g" % value


def circle_to_path(cx, cy, r):
    """A circle as two semicircular arcs, starting at its west point."""
    return "M%s,%s a%s,%s 0 1,0 %s,0 a%s,%s 0 1,0 -%s,0" % (
        trim(cx - r), trim(cy), trim(r), trim(r),
        trim(2 * r), trim(r), trim(r), trim(2 * r),
    )


def load(slug, svg_dir):
    if svg_dir:
        with open(os.path.join(svg_dir, slug + ".svg"), "rb") as handle:
            return handle.read()
    with urllib.request.urlopen("%s/icons/%s.svg" % (BASE, slug), timeout=30) as response:
        return response.read()


def convert(slug, drawable, svg_dir, problems):
    root = ET.fromstring(load(slug, svg_dir))

    # Asserted rather than assumed: every one of these is a property the
    # generated <path> attributes below hard-code, so a source that stopped
    # matching would be converted into a lie.
    for attribute, expected in (
        ("fill", "none"),
        ("stroke-width", "2"),
        ("stroke-linecap", "round"),
        ("stroke-linejoin", "round"),
        ("viewBox", "0 0 24 24"),
    ):
        actual = root.get(attribute)
        if actual != expected:
            problems.append("%s: %s is %r, expected %r" % (slug, attribute, actual, expected))

    datas, note = [], ""
    for element in root:  # document order, so the drawing stacks as authored
        tag = element.tag.replace(NS, "")
        if tag == "path":
            datas.append(element.get("d"))
        elif tag == "circle":
            cx, cy, r = (float(element.get(key)) for key in ("cx", "cy", "r"))
            datas.append(circle_to_path(cx, cy, r))
            note = CIRCLE_NOTE.format(cx=trim(cx), cy=trim(cy), r=trim(r))
        else:
            problems.append(
                "%s: <%s> has no conversion here. Add one deliberately — "
                "dropping it would lose part of the drawing silently." % (slug, tag)
            )

    if not datas:
        problems.append("%s: nothing to draw" % slug)

    licence = "ISC; notice in licenses/Lucide-ISC.txt."
    if slug in FEATHER:
        licence = ("ISC, and MIT as well — this one derives from Feather.\n"
                   "    Both notices are in licenses/Lucide-ISC.txt.")

    body = HEADER.format(slug=slug, version=VERSION, licence=licence, note=note)
    for d in datas:
        body += PATH.format(d=d)
    return body + "</vector>\n", len(datas), bool(note)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--svg-dir", help="convert a local copy instead of fetching")
    parser.add_argument("--out", default=OUT, help="drawable directory to write")
    args = parser.parse_args()

    if not os.path.isdir(args.out):
        sys.exit("no drawable directory at %s — run this from the repo root" % args.out)

    problems = []
    for slug, drawable in sorted(ICONS.items()):
        body, count, circled = convert(slug, drawable, args.svg_dir, problems)
        with open(os.path.join(args.out, drawable + ".xml"), "w") as handle:
            handle.write(body)
        print("%-14s -> %-22s %d path(s)%s" % (
            slug, drawable + ".xml", count, "  [circle converted]" if circled else ""))

    if problems:
        print("\nFAILED:", file=sys.stderr)
        for problem in problems:
            print("  " + problem, file=sys.stderr)
        sys.exit(1)
    print("\n%d drawables from lucide-static %s" % (len(ICONS), VERSION))


if __name__ == "__main__":
    main()
